add_newline = true

[character]
success_symbol = "ğŸğŸ’¬"
error_symbol = "ğŸ¥©ğŸ’¢"

[directory]
style = "#ba55d3"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "

[docker_context]
symbol = "ğŸ‹ "

[package]
disabled = true
