add_newline = true

[character]
style_success = "#ff69b4"
symbol = "ğŸğŸ’¬"
error_symbol = "ğŸ¥©ğŸ’¢"
use_symbol_for_status = true

[directory]
style = "#ba55d3"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "

[git_commit]
prefix = "aaaa"

[docker_context]
symbol = "ğŸ‹ "

[package]
disabled = true
